In [46]:
# Corona Virus Predict
# Based on logistic regression model


In [ ]:
import pandas as pd

In [8]:
data = pd.read_csv('final_data.csv')

In [9]:
data.head() 

Fiver  Bodypain  RunnuNose  BreathingProb  CoughProb  LOSOFAT  Diabetes  \
0      1         1          1              1          1        0         1   
1      1         1          1              1          1        0         1   
2      1         1          1              1          1        0         1   
3      1         1          1              1          1        0         1   
4      1         1          1              1          1        0         1   

   Hypertension  Lung Disease  Heart Disease  KidneyDisorder  Age_0-9  \
0             1             1              1               0        1   
1             1             1              1               0        1   
2             1             1              1               0        1   
3             1             1              1               0        1   
4             1             1              1               0        1   

   Age_10-19  Age_20-24  Age_25-59  Age_60+  InfectionProbablity  
0          0          0          0        0                    1  
1          0          0          0        0                    1  
2          0          0          0        0                    1  
3          0          0          0        0                    0  
4          0          0          0        0                    1

In [10]:
data.describe()

Fiver      Bodypain     RunnuNose  BreathingProb    CoughProb  \
count  31680.00000  31680.000000  31680.000000   31680.000000  31680.00000   
mean       0.31250      0.500000      0.562500       0.500000      0.31250   
std        0.46352      0.500008      0.496086       0.500008      0.46352   
min        0.00000      0.000000      0.000000       0.000000      0.00000   
25%        0.00000      0.000000      0.000000       0.000000      0.00000   
50%        0.00000      0.500000      1.000000       0.500000      0.00000   
75%        1.00000      1.000000      1.000000       1.000000      1.00000   
max        1.00000      1.000000      1.000000       1.000000      1.00000   

            LOSOFAT      Diabetes  Hypertension  Lung Disease  Heart Disease  \
count  31680.000000  31680.000000  31680.000000  31680.000000   31680.000000   
mean       0.062500      0.363636      0.545455      0.545455       0.363636   
std        0.242065      0.481053      0.497937      0.497937       0.481053   
min        0.000000      0.000000      0.000000      0.000000       0.000000   
25%        0.000000      0.000000      0.000000      0.000000       0.000000   
50%        0.000000      0.000000      1.000000      1.000000       0.000000   
75%        0.000000      1.000000      1.000000      1.000000       1.000000   
max        1.000000      1.000000      1.000000      1.000000       1.000000   

       KidneyDisorder       Age_0-9     Age_10-19     Age_20-24     Age_25-59  \
count    31680.000000  31680.000000  31680.000000  31680.000000  31680.000000   
mean         0.090909      0.200000      0.200000      0.200000      0.200000   
std          0.287484      0.400006      0.400006      0.400006      0.400006   
min          0.000000      0.000000      0.000000      0.000000      0.000000   
25%          0.000000      0.000000      0.000000      0.000000      0.000000   
50%          0.000000      0.000000      0.000000      0.000000      0.000000   
75%          0.000000      0.000000      0.000000      0.000000      0.000000   
max          1.000000      1.000000      1.000000      1.000000      1.000000   

            Age_60+  InfectionProbablity  
count  31680.000000         31680.000000  
mean       0.200000             0.501231  
std        0.400006             0.500006  
min        0.000000             0.000000  
25%        0.000000             0.000000  
50%        0.000000             1.000000  
75%        0.000000             1.000000  
max        1.000000             1.000000

In [11]:
# Test Train Spliting

In [12]:
import numpy as np

In [13]:
def data_split(data,ratio):
    np.random.seed(45)
    shuffled = np.random.permutation(len(data))
    test_set_size = int(len(data)*ratio)
    test_data = shuffled[:test_set_size]
    train_data = shuffled[test_set_size:]
    return data.iloc[train_data],data.iloc[test_data]

In [14]:
np.random.permutation(10)



array([4, 0, 8, 5, 7, 1, 6, 2, 9, 3])

In [15]:
train,test = data_split(data,.33)  #Put the Ratio here in which we want to split the data 

In [16]:
train


Fiver  Bodypain  RunnuNose  BreathingProb  CoughProb  LOSOFAT  \
7091       0         1          1              1          1        0   
26169      0         1          1              1          0        0   
15225      1         1          0              0          0        0   
18623      0         0          0              1          0        0   
16002      0         0          1              1          1        0   
...      ...       ...        ...            ...        ...      ...   
28192      0         1          1              1          1        0   
6012       0         0          0              1          0        0   
30339      0         1          1              1          1        0   
6558       1         1          1              1          0        0   
23499      1         1          1              0          0        0   

       Diabetes  Hypertension  Lung Disease  Heart Disease  KidneyDisorder  \
7091          0             0             1              1               0   
26169         1             1             0              0               0   
15225         1             0             0              0               0   
18623         1             1             1              1               0   
16002         1             1             0              0               0   
...         ...           ...           ...            ...             ...   
28192         0             1             0              0               0   
6012          0             1             0              0               0   
30339         0             0             0              1               0   
6558          0             0             1              1               0   
23499         1             1             1              1               0   

       Age_0-9  Age_10-19  Age_20-24  Age_25-59  Age_60+  InfectionProbablity  
7091         0          1          0          0        0                    0  
26169        0          0          0          0        1                    0  
15225        0          0          1          0        0                    0  
18623        0          0          1          0        0                    0  
16002        0          0          1          0        0                    1  
...        ...        ...        ...        ...      ...                  ...  
28192        0          0          0          0        1                    1  
6012         1          0          0          0        0                    1  
30339        0          0          0          0        1                    1  
6558         0          1          0          0        0                    0  
23499        0          0          0          1        0                    0  

[21226 rows x 17 columns]

In [17]:
test

Fiver  Bodypain  RunnuNose  BreathingProb  CoughProb  LOSOFAT  \
12818      1         1          1              1          0        0   
28108      1         0          0              0          0        0   
19995      0         1          1              0          0        0   
31644      0         0          0              0          0        1   
6114       0         0          0              0          1        0   
...      ...       ...        ...            ...        ...      ...   
11166      1         0          0              0          0        0   
7917       0         0          1              0          0        0   
18487      0         0          0              1          1        0   
11170      1         0          0              0          0        0   
5377       0         1          0              0          0        0   

       Diabetes  Hypertension  Lung Disease  Heart Disease  KidneyDisorder  \
12818         1             1             1              0               0   
28108         0             0             0              0               1   
19995         0             1             1              0               0   
31644         0             0             1              0               0   
6114          1             0             0              0               0   
...         ...           ...           ...            ...             ...   
11166         0             1             0              0               0   
7917          0             0             0              0               1   
18487         1             1             1              1               0   
11170         0             1             0              0               0   
5377          0             0             1              0               0   

       Age_0-9  Age_10-19  Age_20-24  Age_25-59  Age_60+  InfectionProbablity  
12818        0          0          1          0        0                    1  
28108        0          0          0          0        1                    0  
19995        0          0          0          1        0                    1  
31644        0          0          0          0        1                    1  
6114         1          0          0          0        0                    1  
...        ...        ...        ...        ...      ...                  ...  
11166        0          1          0          0        0                    1  
7917         0          1          0          0        0                    1  
18487        0          0          1          0        0                    1  
11170        0          1          0          0        0                    0  
5377         1          0          0          0        0                    0  

[10454 rows x 17 columns]

In [18]:
X_train = train[['Fiver','Bodypain','RunnuNose','BreathingProb','CoughProb','LOSOFAT','Diabetes','Hypertension','Lung Disease','Heart Disease','KidneyDisorder','Age_0-9','Age_10-19','Age_20-24','Age_25-59','Age_60+']].to_numpy()
X_test = test[['Fiver','Bodypain','RunnuNose','BreathingProb','CoughProb','LOSOFAT','Diabetes','Hypertension','Lung Disease','Heart Disease','KidneyDisorder','Age_0-9','Age_10-19','Age_20-24','Age_25-59','Age_60+']].to_numpy()

In [19]:
y_train = train[['InfectionProbablity']].to_numpy().reshape(21226 , )
y_test = test[['InfectionProbablity']].to_numpy().reshape(10454 , )

In [20]:
y_test

array([1, 0, 1, ..., 1, 0, 0], dtype=int64)

In [21]:
y_train

array([0, 0, 0, ..., 1, 0, 0], dtype=int64)

In [22]:
X_train

array([[0, 1, 1, ..., 0, 0, 0],
       [0, 1, 1, ..., 0, 0, 1],
       [1, 1, 0, ..., 1, 0, 0],
       ...,
       [0, 1, 1, ..., 0, 0, 1],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 1, 0]], dtype=int64)

In [23]:
X_test

array([[1, 1, 1, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 1],
       [0, 1, 1, ..., 0, 1, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0]], dtype=int64)

In [24]:
X_train

array([[0, 1, 1, ..., 0, 0, 0],
       [0, 1, 1, ..., 0, 0, 1],
       [1, 1, 0, ..., 1, 0, 0],
       ...,
       [0, 1, 1, ..., 0, 0, 1],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 1, 0]], dtype=int64)

In [33]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [34]:
clf=LogisticRegression()

In [35]:
clf.fit(X_train,y_train)

LogisticRegression()

In [36]:
info_input = [1,1,0,1,0,1,0,1,0,1,0,0,0,0,0,1]

In [37]:
probablity_info = clf.predict_proba([info_input])[0][1]

In [38]:
round(probablity_info*100)

54.0

In [39]:
accuracy = clf.score(X_train,y_train)

In [40]:
print(accuracy)

0.5159238669556204
